
[
	Exposed = Window
] interface HubbleWinform : HubbleXobj {

	// Message API
	HubbleNode getGrid(Element elem);
	HubbleNode getGrid(DOMString galaxyName, [DefaultValue = Undefined] optional DOMString clusterName, [DefaultValue = Undefined] optional DOMString gridName);
	HubbleGalaxy getGalaxy(DOMString galaxyName);
	void SyncCtrlTextChange(DOMString strcontrols, [DefaultValue = Undefined] optional ApplicationCallback callback);

	void DispatchGridEvent(Element elem, DOMString eventName);

	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute boolean isReady;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute long formType;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute long long handle;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode mdibindgrid;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode mdiwebbindgrid;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleWinform mdiParent;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleWinform activeMDIChild;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onGridCreated;
	attribute EventHandler onLoadMdiChildWinForm;
	attribute EventHandler onCloudMessageForWinForm;
	attribute EventHandler onGalaxyCreated;
	attribute EventHandler onAllMdiChildRemoved;
	attribute EventHandler onMdiChildWinFormReady;
	attribute EventHandler onMdiWinFormReady;
	attribute EventHandler onWinFormReady;
	attribute EventHandler onWinFormClosed;
	attribute EventHandler onMdiChildActivate;
};
