
[
	Exposed = Window
] interface HubbleWinform : EventTarget {

	// Message API
	void sendMessage([DefaultValue = Undefined] optional HubbleXobj msg,
		[DefaultValue = Undefined] optional ApplicationCallback callback);
	void addEventListener(DOMString eventName, ApplicationCallback callback);
	void addEventListener(DOMString subObjName, DOMString eventName, ApplicationCallback callback);
	HubbleNode getGrid(DOMString galaxyName, DOMString clusterName, DOMString gridName);
	void removeEventListener(DOMString eventName);
	void SyncCtrlTextChange(DOMString strcontrols, [DefaultValue = Undefined] optional ApplicationCallback callback);

	readonly attribute boolean isReady;
	readonly attribute long formType;
	readonly attribute long long handle;
	readonly attribute DOMString name;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleXobj xobj;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode mdibindgrid;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode mdiwebbindgrid;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleWinform mdiParent;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onGridCreated;
	attribute EventHandler onLoadMdiChildWinForm;
	attribute EventHandler onCloudMessageForWinForm;
	attribute EventHandler onGalaxyCreated;
	attribute EventHandler onAllMdiChildRemoved;
	attribute EventHandler onMdiChildWinFormReady;
	attribute EventHandler onMdiWinFormReady;
	attribute EventHandler onWinFormReady;
	attribute EventHandler onWinFormClosed;
	attribute EventHandler onMdiChildActivate;
};
